In Travis build, install hdf5 dependency
This is based on the error in the recent builds:
```
configure: error: hdf5 does not seem to be installed on your platform.
  Please install the hdf5 library.
  The required HDF5 library files can be installed as follows:
      - Debian-based (e.g. Debian >= 8.0, Ubuntu >= 15.04): 'sudo apt-get install libhdf5-dev'
        - Old Debian-based (e.g Debian < 8.0, Ubuntu < 15.04): Install from source (see INSTALL)
        - OS X using Homebrew: 'brew install homebrew/science/hdf5'
        - RPM-based (e.g Fedora): 'sudo yum install hdf5-devel'
ERROR: configuration failed for package hdf5r
```